from __future__ import annotations

import logging
import math
from typing import TYPE_CHECKING

import torch
from transformers import AutoTokenizer

from mteb.models.model_implementations.rerankers_custom import RerankerWrapper
from mteb.models.model_meta import ModelMeta, ScoringFunction
from mteb.models.vllm_wrapper import VllmGenerationWrapper

if TYPE_CHECKING:
    from torch.utils.data import DataLoader

    from mteb.abstasks.task_metadata import TaskMetadata
    from mteb.types import Array, BatchedInput, PromptType

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class Rank1Reranker(RerankerWrapper):
    name: str = "rank1"

    def __init__(
        self,
        model_name_or_path: str = "jhu-clsp/rank1-7b",
        batch_size: int = 999999999999,
        context_size: int = 16000,
        max_output_tokens: int = 8192,
        fp_options: str = "float16",
        num_gpus: int = 1,
        device: str = "cuda",
        force_rethink: int = 0,
        dataset_prompt: str | None = None,
        **kwargs,
    ):
        """
        rank1 is a reasoning reranker model (using test-time compute) which generates a reasoning chain before deciding true or false

        Args:
            model_name_or_path: Path to the model or name of the model on HuggingFace Hub
            batch_size: Maximum batch size for processing (default: very large number to let vLLM handle batching)
            context_size: Maximum context length for the model (default: 4096)
            max_output_tokens: Maximum number of tokens to generate (default: 1024)
            fp_options: Floating point precision to use, e.g. 'float16' (default: 'float16')
            num_gpus: Number of GPUs to use for tensor parallelism (default: 1)
            device: Device to load the model on (default: 'cuda')
            force_rethink: Number of times to force model to rethink its answer (default: 0)
            **kwargs: Additional keyword arguments passed to parent RerankerWrapper
        """
        super().__init__(
            model_name_or_path, batch_size=batch_size, fp_options=fp_options, **kwargs
        )

        self.context_size = context_size
        self.max_output_tokens = max_output_tokens
        self.num_gpus = num_gpus
        self.device = device
        self.force_rethink = force_rethink
        self.model_name_or_path = model_name_or_path
        self.dataset_prompt = dataset_prompt

        self.wrapper = VllmGenerationWrapper(
            model=model_name_or_path,
            tensor_parallel_size=int(num_gpus),
            trust_remote_code=True,
            max_model_len=context_size,
            gpu_memory_utilization=0.5,
            dtype=fp_options,
        )
        self.model = self.wrapper.llm
        self.SamplingParams = self.wrapper.SamplingParams

        # Initialize tokenizer with max length of
        self.tokenizer = AutoTokenizer.from_pretrained(model_name_or_path)
        self.tokenizer.padding_side = "left"
        self.tokenizer.pad_token = self.tokenizer.eos_token

        # Cache commonly used token IDs
        self.true_token = self.tokenizer(" true", add_special_tokens=False).input_ids[0]
        self.false_token = self.tokenizer(" false", add_special_tokens=False).input_ids[
            0
        ]
        self.think_token = self.tokenizer(
            "<think>", add_special_tokens=False
        ).input_ids[0]
        self.think_end_token = self.tokenizer(
            "</think>", add_special_tokens=False
        ).input_ids[-1]

        self.sampling_params = self.SamplingParams(
            temperature=0,
            max_tokens=max_output_tokens,
            logprobs=20,
            stop=["</think> true", "</think> false"],
            skip_special_tokens=False,
        )

    def _fix_incomplete_responses(
        self, original_prompts: list[str], generated_texts: list[str]
    ) -> tuple[list[str], list[int], list[float]]:
        """
        This function is used to fix incomplete responses from the vLLM model. In some cases the model does not generate the end </think> token.
            In these cases, we should force it to generate it so that we have some prediction.

        Args:
            original_prompts: The original prompts that were used to generate the texts
            generated_texts: The texts that were generated by the vLLM model

        Returns:
            final_texts: The texts that were generated by the vLLM model + the outputs from the forcing step
            token_counts: The number of tokens in the texts total
            scores: The scores of the texts
        """

        cleaned_texts = []
        for text in generated_texts:
            text = text.rstrip()
            if not text.endswith((".", "!", "?")):
                last_punct = max(text.rfind("."), text.rfind("!"), text.rfind("?"))
                if last_punct != -1:
                    text = text[: last_punct + 1]
            cleaned_texts.append(text.strip())

        forced_prompts = [
            f"{original_prompt}\n{cleaned_text}\n</think>"
            for original_prompt, cleaned_text in zip(original_prompts, cleaned_texts)
        ]

        new_sampling_args = self.SamplingParams(
            temperature=0,
            max_tokens=1,
            logprobs=20,
            allowed_token_ids=[self.true_token, self.false_token],
            skip_special_tokens=False,
        )
        outputs = self.model.generate(forced_prompts, new_sampling_args)

        # get the next token logits of just the next token
        all_final_texts = []
        all_token_counts = []
        all_scores = []
        for i in range(len(outputs)):
            text = outputs[i].outputs[0].text
            token_count = len(outputs[i].outputs[0].token_ids)

            try:
                final_logits = outputs[i].outputs[0].logprobs[-1]
            except Exception as e:
                print(f"Error: {e} on getting logprobs, setting score to 0.5")
                all_scores.append(0.5)
                all_token_counts.append(token_count)
                all_final_texts.append(text)
                continue

            has_true = self.true_token in final_logits
            has_false = self.false_token in final_logits

            if has_true and has_false:
                true_logit = final_logits[self.true_token].logprob
                false_logit = final_logits[self.false_token].logprob
            elif has_true or has_false:
                # One token is missing from the top-k logprobs. The generated token
                # is always present; the absent one has a very low probability, so
                # use (min visible logprob - 10) as a conservative lower bound.
                floor_logprob = min(lp.logprob for lp in final_logits.values()) - 10.0
                true_logit = (
                    final_logits[self.true_token].logprob if has_true else floor_logprob
                )
                false_logit = (
                    final_logits[self.false_token].logprob
                    if has_false
                    else floor_logprob
                )
            else:
                print(
                    f"Neither true nor false token found in logprobs, setting score to 0.5: {final_logits}"
                )
                all_scores.append(0.5)
                all_token_counts.append(token_count)
                all_final_texts.append(text)
                continue

            true_score = math.exp(true_logit)
            false_score = math.exp(false_logit)
            score = true_score / (true_score + false_score)

            all_final_texts.append(text)
            all_token_counts.append(token_count)
            all_scores.append(score)

        return all_final_texts, all_token_counts, all_scores

    def truncate_input(self, text: str) -> str:
        """
        Truncate the input text to the context size. This is not used, except if you are using the Llama 8B quantized model
        """
        if len(self.tokenizer(text)["input_ids"]) >= self.context_size:
            return self.tokenizer.decode(
                self.tokenizer(text)["input_ids"][: self.context_size]
            )
        else:
            return text

    def _process_with_vllm(self, prompts):
        """
        vLLM is significantly faster than HF, so we use it by default. This function handles the cases where the model does not generate the end </think> token.

        Args:
            prompts: The prompts to generate from

        Returns:
            outputs: The outputs from the vLLM model
        """
        # prompts = [self.truncate_input(prompt) for prompt in prompts]
        outputs = self.model.generate(prompts, self.sampling_params)

        # Pre-allocate lists with None values
        total_length = len(prompts)
        all_outputs = [None] * total_length
        all_output_token_counts = [None] * total_length
        all_scores = [None] * total_length

        incomplete_prompts = []
        incomplete_texts = []
        incomplete_indices = []

        # Process complete responses first
        for i, output in enumerate(outputs):
            text = output.outputs[0].text
            try:
                final_logits = output.outputs[0].logprobs[-1]
            except Exception as e:
                print(f"Error: {e} on getting final logits: {output.outputs[0]}")
                incomplete_prompts.append(prompts[i])
                incomplete_texts.append(text)
                incomplete_indices.append(i)
                continue

            if (
                self.true_token not in final_logits
                or self.false_token not in final_logits
            ):
                incomplete_prompts.append(prompts[i])
                incomplete_texts.append(text)
                incomplete_indices.append(i)
                continue

            token_count = len(output.outputs[0].token_ids)
            true_logit = final_logits[self.true_token].logprob
            false_logit = final_logits[self.false_token].logprob
            true_score = math.exp(true_logit)
            false_score = math.exp(false_logit)
            score = true_score / (true_score + false_score)

            all_outputs[i] = text
            all_output_token_counts[i] = token_count
            all_scores[i] = score

        # Handle incomplete responses
        if incomplete_indices:
            fixed_texts, fixed_counts, fixed_scores = self._fix_incomplete_responses(
                incomplete_prompts, incomplete_texts
            )

            # Fill in the fixed responses at their original positions
            for orig_idx, (text, count, score) in zip(
                incomplete_indices, zip(fixed_texts, fixed_counts, fixed_scores)
            ):
                all_outputs[orig_idx] = text
                all_output_token_counts[orig_idx] = count
                all_scores[orig_idx] = score

        return all_outputs, all_output_token_counts, all_scores

    def return_prompt(self, query, doc_content, prompt) -> str:
        query = prompt.replace("FILL_QUERY_HERE", query) if prompt else query
        return (
            "Determine if the following passage is relevant to the query. "
            "Answer only with 'true' or 'false'.\n"
            f"Query: {query}\n"
            f"Passage: {doc_content}\n"
            "<think>"
        )  # force the model to start with this

    def _prepare_prompts_for_rethink(
        self, prompts: list[str], texts: list[str], rethink_text: str = "Wait"
    ) -> list[str]:
        """Prepare prompts for the rethinking step."""
        full_texts = [p + t for p, t in zip(prompts, texts)]
        stripped_texts = [t.split("</think>")[0] for t in full_texts]
        just_generated_texts = [t.split("</think>")[0] for t in full_texts]
        return [s + f"\n{rethink_text}" for s in stripped_texts], just_generated_texts

    @torch.inference_mode()
    def predict(
        self,
        inputs1: DataLoader[BatchedInput],
        inputs2: DataLoader[BatchedInput],
        *,
        task_metadata: TaskMetadata,
        hf_split: str,
        hf_subset: str,
        prompt_type: PromptType | None = None,
        **kwargs,
    ) -> Array:
        queries = [text for batch in inputs1 for text in batch["text"]]
        instructions = None
        if "instruction" in inputs1.dataset.features:
            instructions = [text for batch in inputs1 for text in batch["instruction"]]
        passages = [text for batch in inputs2 for text in batch["text"]]

        if instructions is not None and instructions[0] is not None:
            queries = [
                f"{q} {i}".strip() if q.strip() != i.strip() else q.strip()
                for i, q in zip(instructions, queries)
            ]

        prompts = [
            self.return_prompt(query, passage, self.dataset_prompt)
            for query, passage in zip(queries, passages)
        ]
        print(f"Example prompt: ```\n{prompts[0]}\n```")

        texts, token_counts, scores = self._process_with_vllm(prompts)
        while self.force_rethink:
            revised_prompts, previously_generated_texts = (
                self._prepare_prompts_for_rethink(prompts, texts)
            )
            new_texts, new_token_counts, new_scores = self._process_with_vllm(
                revised_prompts
            )
            # add to the previous output
            texts = [prev + f"{new_text}" for prev, new_text in zip(texts, new_texts)]
            scores = new_scores
            token_counts = [
                prev_token_count + new_token_count
                for prev_token_count, new_token_count in zip(
                    token_counts, new_token_counts
                )
            ]
            self.force_rethink -= 1

        return scores


RANK1_CITATION = """@misc{weller2025rank1testtimecomputereranking,
  title={Rank1: Test-Time Compute for Reranking in Information Retrieval},
  author={Weller, Orion and Ricci, Kathryn and Yang, Eugene and Yates, Andrew and Lawrie, Dawn and Van Durme, Benjamin},
  journal={arXiv preprint arXiv:2502.18418},
  year={2025}
}"""

RANK1_TRAINING_DATASET = {
    "SciFact",
    "ClimateFEVER",
    "TRECCOVID",
    "ArguAna",
    "DBPedia",
    "FiQA2018",
    "NFCorpus",
    "Touche2020",
    "SCIDOCS",
    "BrightRetrieval aops",
    "BrightRetrieval theoremqa questions",
    "BrightRetrieval leetcode",
    "BrightRetrieval pony",
    "BrightRetrieval",
    "BrightRetrieval theoremqa theorems",
}

rank1_0b5 = ModelMeta(
    loader=Rank1Reranker,
    loader_kwargs={},
    name="jhu-clsp/rank1-0.5b",
    revision="e72a44592d93f7f47a0c3bcd3a19958397278582",
    release_date="2025-03-11",
    languages=None,
    n_parameters=630167424,
    n_active_parameters_override=None,
    n_embedding_parameters=None,
    memory_usage_mb=1202.0,
    max_tokens=32768.0,
    embed_dim=896,
    license="mit",
    open_weights=True,
    public_training_code="https://github.com/orionw/rank1",
    public_training_data="https://huggingface.co/datasets/jhu-clsp/rank1-training-data",
    framework=["PyTorch", "Transformers", "safetensors"],
    reference="https://huggingface.co/jhu-clsp/rank1-0.5b",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=False,
    training_datasets=RANK1_TRAINING_DATASET,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["cross-encoder"],
    citation=RANK1_CITATION,
    contacts=["orionw"],
)
rank1_1b5 = ModelMeta(
    loader=Rank1Reranker,
    loader_kwargs={},
    name="jhu-clsp/rank1-1.5b",
    revision="0b513ca87e0de16ffe17196c6746f28cafaad26b",
    release_date="2025-03-12",
    languages=None,
    n_parameters=1777088000,
    n_active_parameters_override=None,
    n_embedding_parameters=None,
    memory_usage_mb=3390.0,
    max_tokens=131072.0,
    embed_dim=1536,
    license="mit",
    open_weights=True,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "Transformers", "safetensors"],
    reference="https://huggingface.co/jhu-clsp/rank1-1.5b",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=False,
    training_datasets=RANK1_TRAINING_DATASET,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["cross-encoder"],
    citation=RANK1_CITATION,
    contacts=["orionw"],
)
rank1_3b = ModelMeta(
    loader=Rank1Reranker,
    loader_kwargs={},
    name="jhu-clsp/rank1-3b",
    revision="9ab297fbce9b6484b219583f8b86ec872d77ca79",
    release_date="2025-03-11",
    languages=None,
    n_parameters=3397103616,
    n_active_parameters_override=None,
    n_embedding_parameters=None,
    memory_usage_mb=6479.0,
    max_tokens=32768.0,
    embed_dim=2048,
    license="mit",
    open_weights=True,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "Transformers", "safetensors"],
    reference="https://huggingface.co/jhu-clsp/rank1-3b",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=False,
    training_datasets=RANK1_TRAINING_DATASET,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["cross-encoder"],
    citation=RANK1_CITATION,
    contacts=["orionw"],
)
rank1_7b = ModelMeta(
    loader=Rank1Reranker,
    loader_kwargs={},
    name="jhu-clsp/rank1-7b",
    revision="d98c3a2db434d9492eff91cc3fa0ac354367cfb4",
    release_date="2025-02-18",
    languages=None,
    n_parameters=7615616512,
    n_active_parameters_override=None,
    n_embedding_parameters=None,
    memory_usage_mb=14526.0,
    max_tokens=131072.0,
    embed_dim=3584,
    license="mit",
    open_weights=True,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "Transformers", "safetensors"],
    reference="https://huggingface.co/jhu-clsp/rank1-7b",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=False,
    training_datasets=RANK1_TRAINING_DATASET,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["cross-encoder"],
    citation=RANK1_CITATION,
    contacts=["orionw"],
)
rank1_14b = ModelMeta(
    loader=Rank1Reranker,
    loader_kwargs={},
    name="jhu-clsp/rank1-14b",
    revision="4b143af6a46d59834e12a221f19d803e7a069f57",
    release_date="2025-02-18",
    languages=None,
    n_parameters=14770033664,
    n_active_parameters_override=None,
    n_embedding_parameters=None,
    memory_usage_mb=28172.0,
    max_tokens=131072.0,
    embed_dim=5120,
    license="mit",
    open_weights=True,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "Transformers", "safetensors"],
    reference="https://huggingface.co/jhu-clsp/rank1-14b",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=False,
    training_datasets=RANK1_TRAINING_DATASET,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["cross-encoder"],
    citation=RANK1_CITATION,
    contacts=["orionw"],
)
rank1_32b = ModelMeta(
    loader=Rank1Reranker,
    loader_kwargs={},
    name="jhu-clsp/rank1-32b",
    revision="55ebd020eafbd145ac44e68f50edc7f59952d67d",
    release_date="2025-02-19",
    languages=None,
    n_parameters=32763876352,
    n_active_parameters_override=None,
    n_embedding_parameters=None,
    memory_usage_mb=62492.0,
    max_tokens=131072.0,
    embed_dim=5120,
    license="mit",
    open_weights=True,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "Transformers", "safetensors"],
    reference="https://huggingface.co/jhu-clsp/rank1-32b",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=False,
    training_datasets=RANK1_TRAINING_DATASET,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["cross-encoder"],
    citation=RANK1_CITATION,
    contacts=["orionw"],
)
rank1_mistral_2501_24b = ModelMeta(
    loader=Rank1Reranker,
    loader_kwargs={},
    name="jhu-clsp/rank1-mistral-2501-24b",
    revision="039dec6eb7b2242320e4e65b1639dc0f23f28005",
    release_date="2025-02-18",
    languages=None,
    n_parameters=23573058560,
    n_active_parameters_override=None,
    n_embedding_parameters=None,
    memory_usage_mb=44962.0,
    max_tokens=32768.0,
    embed_dim=5120,
    license="mit",
    open_weights=True,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "safetensors"],
    reference="https://huggingface.co/jhu-clsp/rank1-mistral-2501-24b",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=False,
    training_datasets=RANK1_TRAINING_DATASET,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["cross-encoder"],
    citation=RANK1_CITATION,
    contacts=["orionw"],
)
rank1_llama3_8b = ModelMeta(
    loader=Rank1Reranker,
    loader_kwargs={},
    name="jhu-clsp/rank1-llama3-8b",
    revision="107571dc6d3f09b5e0c7cbc310997f7e9dee8371",
    release_date="2025-02-18",
    languages=None,
    n_parameters=8030785536,
    n_active_parameters_override=None,
    n_embedding_parameters=None,
    memory_usage_mb=15318.0,
    max_tokens=8192.0,
    embed_dim=4096,
    license="mit",
    open_weights=True,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "safetensors"],
    reference="https://huggingface.co/jhu-clsp/rank1-llama3-8b",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=False,
    training_datasets=RANK1_TRAINING_DATASET,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["cross-encoder"],
    citation=RANK1_CITATION,
    contacts=["orionw"],
)
rank1_7b_awq = ModelMeta(
    loader=Rank1Reranker,
    loader_kwargs={},
    name="jhu-clsp/rank1-7b-awq",
    revision="ded950ef03edf9561fe2f9978474bda36ccb03ff",
    release_date="2025-02-22",
    languages=None,
    n_parameters=1963340288,
    n_active_parameters_override=None,
    n_embedding_parameters=None,
    memory_usage_mb=5313.0,
    max_tokens=131072.0,
    embed_dim=3584,
    license="mit",
    open_weights=True,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "safetensors"],
    reference="https://huggingface.co/jhu-clsp/rank1-7b-awq",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=False,
    training_datasets=RANK1_TRAINING_DATASET,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["cross-encoder"],
    citation=RANK1_CITATION,
    contacts=["orionw"],
)
rank1_14b_awq = ModelMeta(
    loader=Rank1Reranker,
    loader_kwargs={},
    name="jhu-clsp/rank1-14b-awq",
    revision="004e38435afd70309fb72c0703c4981ffdd8c1e5",
    release_date="2025-02-22",
    languages=None,
    n_parameters=3325604864,
    n_active_parameters_override=None,
    n_embedding_parameters=None,
    memory_usage_mb=9518.0,
    max_tokens=131072.0,
    embed_dim=5120,
    license="mit",
    open_weights=True,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "safetensors"],
    reference="https://huggingface.co/jhu-clsp/rank1-14b-awq",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=False,
    training_datasets=RANK1_TRAINING_DATASET,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["cross-encoder"],
    citation=RANK1_CITATION,
    contacts=["orionw"],
)
rank1_32b_awq = ModelMeta(
    loader=Rank1Reranker,
    loader_kwargs={},
    name="jhu-clsp/rank1-32b-awq",
    revision="a6e8532ca34f1e1db923f042a5e7dcccffa97923",
    release_date="2025-02-22",
    languages=None,
    n_parameters=5733225472,
    n_active_parameters_override=None,
    n_embedding_parameters=None,
    memory_usage_mb=18433.0,
    max_tokens=131072.0,
    embed_dim=5120,
    license="mit",
    open_weights=True,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "safetensors"],
    reference="https://huggingface.co/jhu-clsp/rank1-32b-awq",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=False,
    training_datasets=RANK1_TRAINING_DATASET,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["cross-encoder"],
    citation=RANK1_CITATION,
    contacts=["orionw"],
)
rank1_mistral_2501_24b_awq = ModelMeta(
    loader=Rank1Reranker,
    loader_kwargs={},
    name="jhu-clsp/rank1-mistral-2501-24b-awq",
    revision="c1c5fa922c6b9677986502dca587de80de0c08ee",
    release_date="2025-02-22",
    languages=None,
    n_parameters=4317352960,
    n_active_parameters_override=None,
    n_embedding_parameters=None,
    memory_usage_mb=13576.0,
    max_tokens=32768.0,
    embed_dim=5120,
    license="mit",
    open_weights=True,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "safetensors"],
    reference="https://huggingface.co/jhu-clsp/rank1-mistral-2501-24b-awq",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=False,
    training_datasets=RANK1_TRAINING_DATASET,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["cross-encoder"],
    citation=RANK1_CITATION,
    contacts=["orionw"],
)
rank1_llama3_8b_awq = ModelMeta(
    loader=Rank1Reranker,
    loader_kwargs={},
    name="jhu-clsp/rank1-llama3-8b-awq",
    revision="4f8a73ccfc018bd5556ce82342cbacc9248d4cef",
    release_date="2025-02-22",
    languages=None,
    n_parameters=1985220608,
    n_active_parameters_override=None,
    n_embedding_parameters=None,
    memory_usage_mb=5464.0,
    max_tokens=8192.0,
    embed_dim=4096,
    license="mit",
    open_weights=True,
    public_training_code=None,
    public_training_data=None,
    framework=["PyTorch", "safetensors"],
    reference="https://huggingface.co/jhu-clsp/rank1-llama3-8b-awq",
    similarity_fn_name=ScoringFunction.COSINE,
    use_instructions=False,
    training_datasets=RANK1_TRAINING_DATASET,
    adapted_from=None,
    superseded_by=None,
    modalities=["text"],
    model_type=["cross-encoder"],
    citation=RANK1_CITATION,
    contacts=["orionw"],
)
